//
//  Compiler.swift
//  UserTalk
//
//  Created by Brent Simmons on 4/30/17.
//  Copyright © 2017 Ranchero Software. All rights reserved.
//

import Foundation

struct Compiler {

	static let lock = NSLock()
	
	static func compile(_ text: String, lineBased: Bool) -> CodeTreeNode? {

		let tokenizer = Tokenizer(text, lineBasedScan: lineBased)

		// I don’t know if the parser generated by Bison is thread-safe and/or reentrant.
		// Also: we reference the yyval global to get our code tree.
		// TODO: not use a global.

		lock.lock()

		let parseResult = yyparse() // parse the text, producing parsetree -- if no syntax errors
		let codeTreeNode = yyval  //TODO: how are we going to yyval here?
		// TODO: check for errors

		lock.unlock()

		return codeTreeNode
	}


}
